function [ lower upper ] = loglik_bounds

bigeps = 1e-5;

% 1-2: penalties for walls and occlusions
% 3-6: ideal feature values
% 7-10: falloff -- unnormalized gaussian variance
% 11-14: variance for gaussian noise
% 15-18: mixing between FG and BG
lower = [ bigeps bigeps ...
          0 0 0 0 ...
          bigeps bigeps bigeps bigeps ...
          bigeps bigeps bigeps bigeps ...
          bigeps bigeps bigeps bigeps];
upper = [ 1e+5 1e+5 ...
          1e+5 1e+5 1e+5 1e+5 ...
          500 500 500 500 ...
          1e+4 1e+4 1e+4 1e+4 ...
          1-bigeps 1-bigeps 1-bigeps 1-bigeps ];
