#include "map.h"
#include "map.pb.h"
#include "common_types.h"

namespace indoor_context {
	// Load a map generated by Noah Snavley's Bundler. structure_file
	// should be bundle/bundle.out and image_list should be list.txt
	// generated by RunBundler.
	void LoadBundlerMap(const string& structure_file, const string& image_list_file, Map& map);
	// As above, but uses default filenames. bundle_dir should be the
	// directory containing list.txt.
	void LoadBundlerMap(const string& bundle_dir, Map& map);

	// Load a map from an XML file
	// If all_frames is true then load all frames; otherwise load just the key frames.
	void LoadXmlMap(const string& path,
									Map& map,
									bool all_frames=false);

	// Load a map with ground truth. Store the ground truth in gt_map.
	// If all_frames is true then load all frames; otherwise load just the key frames.
	void LoadXmlMapWithGroundTruth(const string& path,
																 Map& map,
																 proto::TruthedMap& gt_map,
																 bool all_frames=false);
}
