// This file has been generated by Py++.

#include "boost/python.hpp"

#include "math_utils.h"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(indoor_context){
    { //::indoor_context::LogLikelihoodToDistr
    
        typedef ::indoor_context::VecD ( *LogLikelihoodToDistr_function_type )( ::indoor_context::VecD const & );
        
        bp::def( 
            "LogLikelihoodToDistr"
            , LogLikelihoodToDistr_function_type( &::indoor_context::LogLikelihoodToDistr )
            , ( bp::arg("ys") ) );
    
    }

    { //::indoor_context::LogSumExp
    
        typedef double ( *LogSumExp_function_type )( double const *,int );
        
        bp::def( 
            "LogSumExp"
            , LogSumExp_function_type( &::indoor_context::LogSumExp )
            , ( bp::arg("ys"), bp::arg("n") ) );
    
    }

    { //::indoor_context::LogSumExp
    
        typedef double ( *LogSumExp_function_type )( ::indoor_context::VecD const & );
        
        bp::def( 
            "LogSumExp"
            , LogSumExp_function_type( &::indoor_context::LogSumExp )
            , ( bp::arg("ys") ) );
    
    }

    { //::indoor_context::NormalizeLogDistr
    
        typedef void ( *NormalizeLogDistr_function_type )( ::indoor_context::VecD & );
        
        bp::def( 
            "NormalizeLogDistr"
            , NormalizeLogDistr_function_type( &::indoor_context::NormalizeLogDistr )
            , ( bp::arg("ys") ) );
    
    }

    { //::indoor_context::PaddedInt
    
        typedef ::std::string ( *PaddedInt_function_type )( int,int );
        
        bp::def( 
            "PaddedInt"
            , PaddedInt_function_type( &::indoor_context::PaddedInt )
            , ( bp::arg("x"), bp::arg("width") ) );
    
    }
}
